spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bookstore}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.flyway.enabled=true

server.port=8080

application.jwt.secret=${JWT_SECRET}
application.jwt.expiration=86400000

spring.config.import=optional:file:.env[.properties]