spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookstore
    username: bookstore
    password: bookstore
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true

server:
  port: 8080