spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookstore
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true

server:
  port: 8080

application:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 86400000